FROM wiiuenv/devkitppc:20200810

RUN dkp-pacman -Syu && dkp-pacman -S --noconfirm wiiu-sdl2-libs && dkp-pacman -Scc --noconfirm

WORKDIR tmp_build
COPY . .
RUN make -f Makefile.wiiu clean && make -f Makefile.wiiu -j8 && mkdir -p /artifacts/wut/usr && cp -r lib /artifacts/wut/usr && cp -r include /artifacts/wut/usr
WORKDIR /artifacts

FROM scratch
COPY --from=0 /artifacts /artifacts