FROM wiiuenv/devkitppc-with-sdl2:20201002

WORKDIR tmp_build
COPY . .
RUN make -f Makefile.wiiu clean && make -f Makefile.wiiu -j8 && mkdir -p /artifacts/wut/usr && cp -r lib /artifacts/wut/usr && cp -r include /artifacts/wut/usr
WORKDIR /artifacts

FROM scratch
COPY --from=0 /artifacts /artifacts